name: ci

on:
  push:
    branches: [main, master]
  pull_request:

# Añadimos permisos de escritura para que la Action pueda activar el auto-merge y leer los PRs
permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile application
        run: |
          python -m compileall app
          python -m py_compile run.py wsgi.py setup_dynamodb.py setup_s3.py migrate_password_reset.py

      - name: Run tests
        run: pytest

      # Este paso se ejecuta SOLO si es un Pull Request y los tests anteriores pasaron con éxito
      - name: Enable Auto-Merge
        if: github.event_name == 'pull_request'
        run: gh pr merge "${{ github.event.pull_request.number }}" --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
